Areas/admin/Controllers/MakalesAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IBlog.Models;

namespace IBlog.Areas.admin.Controllers
{
    public class MakalesAdminController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: admin/Makales
        public ActionResult Index()
        {
            return View(db.Makaleler.OrderByDescending(x => x.OlusturulmaTarihi).ToList());
        }

        // GET: admin/Makales/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Makale makale = db.Makaleler.Find(id);
            if (makale == null)
            {
                return HttpNotFound();
            }
            return View(makale);
        }

        // GET: admin/Makales/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: admin/Makales/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Makale makale, HttpPostedFileBase Resim)
        {
            //if (ModelState.IsValid)
            //{
            if (Resim != null && Resim.ContentLength > 0)
            {
                var fileName = Path.GetFileName(Resim.FileName);
                var path = Path.Combine(Server.MapPath("~/Resimler"), fileName);
                Resim.SaveAs(path);
                makale.ResimUrl = "/Resimler/" + fileName;
                db.Makaleler.Add(makale);
                makale.OlusturulmaTarihi = DateTime.Now;
                makale.Yazar = "Admin";
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            //return View(makale);
            //db.Makaleler.Add(makale);
            //db.SaveChanges();
            //return RedirectToAction("Index");
            //}
            return View(makale);
        }

        // GET: admin/Makales/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Makale makale = db.Makaleler.Find(id);
            if (makale == null)
            {
                return HttpNotFound();
            }
            return View(makale);
        }

        // POST: admin/Makales/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,KategoriId,Baslik,Icerik,OlusturulmaTarihi,GuncellemeTarihi,ResimUrl,Yazar,OkuyucuSayisi")] Makale makale)
        {
            if (ModelState.IsValid)
            {
                makale.OlusturulmaTarihi = makale.OlusturulmaTarihi;
                makale.GuncellemeTarihi = DateTime.Now;
                db.Entry(makale).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(makale);
        }

        // GET: admin/Makales/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Makale makale = db.Makaleler.Find(id);
            if (makale == null)
            {
                return HttpNotFound();
            }
            return View(makale);
        }

        // POST: admin/Makales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Makale makale = db.Makaleler.Find(id);
            db.Makaleler.Remove(makale);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/admin/Views/MakalesAdmin/Create.cshtml
@model IBlog.Models.Makale

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h2 class="ml-4">Makale Yaz</h2>

@using (Html.BeginForm("Create","MakalesAdmin",FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal ml-2">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Icerik, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Icerik, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.ResimUrl, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("Resim", null, new { @class = "form-control", type = "file" })
            @Html.ValidationMessageFor(model => model.ResimUrl, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.ResimUrl, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("Resim", null, new { @class = "form-control", type = "file" })
            @Html.ValidationMessageFor(model => model.ResimUrl, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Makale Yarat" class="btn btn-success" />
            @Html.ActionLink("Listeye Geri Dön", "Index", null, new { @class = "btn btn-info ml-1" })
        </div>
    </div>
</div>
}

Areas/admin/Views/MakalesAdmin/Delete.cshtml
@model IBlog.Models.Makale

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}


<div class="ml-3">

    <h3>Makale Silme İşlemi</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Baslik)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Baslik)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Icerik)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Icerik)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OlusturulmaTarihi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OlusturulmaTarihi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.GuncellemeTarihi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GuncellemeTarihi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ResimUrl)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ResimUrl)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Yazar)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Yazar)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OkuyucuSayisi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OkuyucuSayisi)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Sil" class="btn btn-danger" />
                @Html.ActionLink("Listeye Geri Dön", "Index", null, new { @class = "btn btn-info" })
            </div>
        }
    </div>
</div>

Areas/admin/Views/MakalesAdmin/Details.cshtml
@model IBlog.Models.Makale

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}
<div style="font-size:1.5rem; padding-left:10px;">

<div class="ml-4">

    <h2>Detaylar</h2>

    <div>
        <h4>Makale</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Baslik)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Baslik)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Icerik)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Icerik)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OlusturulmaTarihi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OlusturulmaTarihi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.GuncellemeTarihi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GuncellemeTarihi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ResimUrl)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ResimUrl)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Yazar)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Yazar)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OkuyucuSayisi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OkuyucuSayisi)
            </dd>

        </dl>
    </div>
</div>
    <p class="pl-2">
@Html.ActionLink("Düzenle", "Edit", new { id = Model.Id }, new { @class = "btn btn-secondary pd" })
@Html.ActionLink("Listeye Geri Dön", "Index", null, new { @class = "btn btn-info" })
    </p>
</div>

Areas/admin/Views/MakalesAdmin/Edit.cshtml
@model IBlog.Models.Makale

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}
<div class="ml-3">

    <h2>Düzenle</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.OlusturulmaTarihi)

            <div class="form-group">
                @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Icerik, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Icerik, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ResimUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ResimUrl, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ResimUrl, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Yazar, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Yazar, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Yazar, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Kaydet" class="btn btn-success" />
                    @Html.ActionLink("Listeye Geri Dön", "Index", null, new { @class = "btn btn-info" })

                </div>
            </div>
        </div>
    }
</div>

Areas/admin/Views/MakalesAdmin/Index.cshtml
@model IEnumerable<IBlog.Models.Makale>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h2 style="margin-left:23px;">Makaleler</h2>

<p>
    @Html.ActionLink("Makale Yaz", "Create", null, new { @class = "btn btn-success ml-4" })
</p>
<table class="table ml-2" style="font-size:1.5rem;" id="dataTable">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Baslik)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OlusturulmaTarihi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Yazar)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Baslik)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OlusturulmaTarihi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Yazar)
            </td>
            <td class="pr-4">
                @Html.ActionLink("Düzenle", "Edit", new { id = item.Id }, new { @class = "btn btn-primary btn-block w-50 ml-5" })
                @Html.ActionLink("Detaylar", "Details", new { id = item.Id }, new { @class = "btn btn-secondary btn-block w-50 ml-5" })
                @Html.ActionLink("Sil", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-block w-50 ml-5" })
            </td>
        </tr>
    }

</table>

@section scripts{
    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable();
        });
        //$("#dataTable").dataTable();
    </script>
}