Models/Makale.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace IBlog.Models
{
    [Table("Makaleler")]
    public class Makale
    {
        public Makale()
        {
            Kategoriler = new HashSet<Kategori>();
            Yorumlar = new HashSet<Yorum>();
        }
        public int Id { get; set; }
        [ScaffoldColumn(false)]
        [Display(Name = "Kategori")]
        public int KategoriId { get; set; }
        [Required]
        [MaxLength(150, ErrorMessage = "En fazla 150 karakter girebilirsiniz.")]
        [Display(Name = "Başlık Adı")]
        public string Baslik { get; set; }
        [Required]
        [Display(Name = "İçerik")]
        public string Icerik { get; set; }

        [Display(Name = "Oluşturulma Tarihi")]
        public DateTime? OlusturulmaTarihi { get; set; }

        [Display(Name = "Güncelleme Tarihi")]
        public DateTime? GuncellemeTarihi { get; set; }

        [Required]
        [Display(Name = "Resim")]
        public string ResimUrl { get; set; }
        public string Yazar { get; set; }

        [Display(Name = "Okuyucu Sayısı")]
        public int OkuyucuSayisi { get; set; }
        public int Like { get; set; }
        public ICollection<Kategori> Kategoriler { get; set; }
        public ICollection<Yorum> Yorumlar { get; set; }
    }
}

Controllers/MakalesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IBlog.Models;

namespace IBlog.Controllers
{
    public class MakalesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Makales
        public ActionResult Index()
        {
            return View(db.Makaleler.ToList());
        }

        // GET: Makales/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Makale makale = db.Makaleler.Find(id);
            if (makale == null)
            {
                return HttpNotFound();
            }
            return View(makale);
        }

        // GET: Makales/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Makales/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Makale makale, HttpPostedFileBase Resim)
        {
            //makale.ResimUrl = Path.Combine(Server.MapPath("~/Resimler"), Resim.FileName);
            //if (ModelState.IsValid)
            //{

                if (Resim != null && Resim.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(Resim.FileName);
                    var path = Path.Combine(Server.MapPath("~/Resimler"), fileName);
                    Resim.SaveAs(path);
                    makale.ResimUrl = "/Resimler/" + fileName;
                    db.Makaleler.Add(makale);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            //}
            return View(makale);
        }

        // GET: Makales/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Makale makale = db.Makaleler.Find(id);
            if (makale == null)
            {
                return HttpNotFound();
            }
            return View(makale);
        }

        // POST: Makales/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,KategoriId,Baslik,Icerik,OlusturulmaTarihi,GuncellemeTarihi,ResimUrl,Yazar,OkuyucuSayisi")] Makale makale)
        {
            if (ModelState.IsValid)
            {
                db.Entry(makale).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(makale);
        }

        // GET: Makales/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Makale makale = db.Makaleler.Find(id);
            if (makale == null)
            {
                return HttpNotFound();
            }
            return View(makale);
        }

        // POST: Makales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Makale makale = db.Makaleler.Find(id);
            db.Makaleler.Remove(makale);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Makales/Create.cshtml
@model IBlog.Models.Makale

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Makales", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Makale</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
            @Html.LabelFor(model => model.KategoriId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KategoriId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
            </div>
        </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Icerik, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OlusturulmaTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OlusturulmaTarihi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OlusturulmaTarihi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GuncellemeTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GuncellemeTarihi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GuncellemeTarihi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ResimUrl, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            @Html.TextBox("Resim", null , new { @class = "form-control", type="file" })
            @Html.ValidationMessageFor(model => model.ResimUrl, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Yazar, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Yazar, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Yazar, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OkuyucuSayisi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OkuyucuSayisi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OkuyucuSayisi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Makales/Delete.cshtml
@model IBlog.Models.Makale

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sil</h2>

<h3>Silmek istediğinizden emin misiniz?</h3>
<div>
    <h4>Makale Silme İşlemi</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.KategoriId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KategoriId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Baslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Baslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Icerik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Icerik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OlusturulmaTarihi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OlusturulmaTarihi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GuncellemeTarihi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GuncellemeTarihi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResimUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResimUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Yazar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Yazar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OkuyucuSayisi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OkuyucuSayisi)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-danger" /> 
            @Html.ActionLink("Listeye Geri Dön", "Index", null, new { @class="btn btn-info"})
        </div>
    }
</div>

Views/Makales/Details.cshtml
@model IBlog.Models.Makale

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Makale</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.KategoriId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KategoriId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Baslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Baslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Icerik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Icerik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OlusturulmaTarihi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OlusturulmaTarihi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GuncellemeTarihi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GuncellemeTarihi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResimUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResimUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Yazar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Yazar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OkuyucuSayisi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OkuyucuSayisi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Makales/Edit.cshtml
@model IBlog.Models.Makale

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="ml-3">

    <h2>Düzenle</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.KategoriId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.KategoriId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Icerik, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OlusturulmaTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OlusturulmaTarihi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OlusturulmaTarihi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.GuncellemeTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GuncellemeTarihi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GuncellemeTarihi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ResimUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ResimUrl, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ResimUrl, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Yazar, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Yazar, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Yazar, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OkuyucuSayisi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OkuyucuSayisi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OkuyucuSayisi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Kaydet" class="btn btn-success" />
                    @Html.ActionLink("Listeye Geri Dön", "Index", null, new { @class = "btn btn-info" })
                </div>
            </div>
        </div>
    }

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Makales/Index.cshtml
@model IEnumerable<IBlog.Models.Makale>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-success"} )
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Baslik)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Icerik)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OlusturulmaTarihi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GuncellemeTarihi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ResimUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Yazar)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OkuyucuSayisi)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Baslik)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Icerik)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OlusturulmaTarihi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GuncellemeTarihi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ResimUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Yazar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OkuyucuSayisi)
            </td>
            <td>
                @Html.ActionLink("Düzenle", "Edit", new { id = item.Id }, new { @class = "btn btn-primary btn-block" }) 
                @Html.ActionLink("Detaylar", "Details", new { id = item.Id }, new { @class = "btn btn-secondary mt-1 mb-1 btn-block" }) 
                @Html.ActionLink("Sil", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-block" })
            </td>
        </tr>
    }

</table>
@section scripts {
    <script>
        $(document).ready(function () {
            $('#nav li').first().addClass('current');
            $('#nav li.current').next().next().addClass('current');
            $('#nav li').first().removeClass('current');
        });
    </script>
    }